In [1]:
import numpy as np
import pandas as pd

In [2]:
def get_unique_value_lengths(dataframe: pd.DataFrame, col_name: str):
    unique_vals = map(lambda r: str(r), dataframe[col_name].unique())
    unique_vals = filter(lambda r: r != 'nan', unique_vals)
    unique_vals = map(lambda r: len(r), unique_vals)
    unique_vals = list(unique_vals)
    return np.array(unique_vals)

def inferred_type(dataframe: pd.DataFrame, col_name: str, max_cat_value_count: int=1000) -> np.dtype:
    is_datetime_col = dataframe[col_name].str.match('(\d{2,4}(-|\/|\\|\.| )\d{2}(-|\/|\\|\.| )\d{2,4})+').all()
    if is_datetime_col:
        return 'datetime'
    
    is_int32 = dataframe[col_name].str.match('\d{1,8}$').all()
    if is_int32:
        return 'int32'
    
    is_float = dataframe[col_name].str.match(r'\d{1,7}(\.\d{1,5})?$').all()
    if is_float:
        return 'float'
    
    unique_vals = dataframe[col_name].unique()
    n_unique = unique_vals.shape[0]

    if n_unique == 2 or n_unique == 3:
        bool_vals = np.array(['(N/A)', 'N', 'Y'], dtype='str')
        possible_bool_vals = np.array(pd.DataFrame(unique_vals).fillna('(N/A)')[0])
        if np.isin(possible_bool_vals, bool_vals).all():
            return 'bool'
    
    if n_unique >= 2 and n_unique < max_cat_value_count:
        unique_val_lengths = get_unique_value_lengths(dataframe, col_name)
        if np.max(unique_val_lengths) > 300:
            # print(f'{col_name} -> {np.max(unique_val_lengths)}')
            return 'object'
        return 'category'

    return 'object'

def clean_icecat(dataframe: pd.DataFrame):
    # Count number of rows per category
    df_count_by_category = dataframe.groupby('category_name').agg({'id': 'count'}).rename(columns={'id': 'n_rows'})

    # Find categories with at least N amount of rows
    categories = list(df_count_by_category[df_count_by_category.n_rows > 20].index)

    # Delete rows with few that N amount of rows per category
    dataframe = dataframe[dataframe.category_name.isin(categories)]

    # Get columns that specify features of the products
    product_feature_columns = list(dataframe.columns)[26:]

    # Find columns that have too few specified values
    n_rows = dataframe.shape[0]
    small_columns = []
    for col in product_feature_columns:
        n_filled = n_rows - dataframe[col].isna().sum()
        if n_filled < 10:
            small_columns.append(col)

    # Find columns that have enough values
    product_features_to_use = [col for col in product_feature_columns if col not in small_columns]
    
    # Create a copy
    df_cleaned = dataframe[['category_name', 'supplier_name'] + product_features_to_use].copy()
    
    # Use proper dtypes
    for col in df_cleaned.columns:
        dtype = inferred_type(df_cleaned, col)
        if dtype == 'int32':
            df_cleaned[col].fillna(0, inplace=True)
        elif dtype == 'float':
            df_cleaned[col].fillna(0.0, inplace=True)
        elif dtype == 'bool':
            df_cleaned[col].fillna('N', inplace=True)
            df_cleaned[col] = df_cleaned[col].str.replace('N', '0')
            df_cleaned[col] = df_cleaned[col].str.replace('Y', '1')
            df_cleaned[col] = df_cleaned[col].astype('int')
        elif dtype == 'category':
            df_cleaned[col].fillna('(N/A)', inplace=True)
            
        df_cleaned[col] = df_cleaned[col].astype(dtype)

    return df_cleaned

def split_train_test(df):
    train = df.sample(frac=.8, random_state=42)
    test = df.loc[~df.index.isin(train.index)]
    return train, test

def compute_column_stats(dataframe: pd.DataFrame):
    dmap = {
        'column': [],
        'suggested_type': [],
        'n_unique': [],
        'len_total': [],
        'len_min': [],
        'len_max': [],
        'len_avg': [],
        'values': [],
        'n_filled': [],
    }

    n_rows = dataframe.shape[0]

    for col in dataframe.columns:
        dmap['column'].append(col)
        dmap['suggested_type'].append(inferred_type(dataframe, col))

        dmap['n_filled'].append( n_rows - dataframe[col].isna().sum() )

        dmap['n_unique'].append(dataframe[col].unique().shape[0])
        unique_val_lengths = get_unique_value_lengths(dataframe, col)
        dmap['len_total'].append(len(unique_val_lengths))
        dmap['len_min'].append(np.min(unique_val_lengths))
        dmap['len_max'].append(np.max(unique_val_lengths))
        dmap['len_avg'].append(np.mean(unique_val_lengths))

        vals = ' | '.join([str(s) for s in list(dataframe[col].unique())[0:5]])
        dmap['values'].append(vals)

    return pd.DataFrame(dmap)

In [3]:
df_data = pd.read_csv('../data/ice-cat-office-products.csv.gz', dtype=str, index_col=0)

In [4]:
df_cleaned_data = clean_icecat(df_data)

In [5]:
df_cleaned_data.head()

,category_name,supplier_name,AC input frequency,AC input voltage,Accessory storage tray,Accuracy touch,Adhesion,Adhesive type,Adjustable angle,Adjustable armrest,...,Weight (without accessories),Wi-Fi,Width,Width (imperial),Window,Windows operating systems supported,Working area,Working width,Writing colours,Zoom capability
2,Fax Machines,HP,(N/A),(N/A),False,(N/A),(N/A),(N/A),False,False,...,0.0,False,0.0,0.0,False,NaN,(N/A),0.0,(N/A),(N/A)
3,Printer Cabinets & Stands,HP,(N/A),(N/A),False,(N/A),(N/A),(N/A),False,False,...,0.0,False,541.0,0.0,False,NaN,(N/A),0.0,(N/A),(N/A)
4,Staples,HP,(N/A),(N/A),False,(N/A),(N/A),(N/A),False,False,...,0.0,False,0.0,0.0,False,NaN,(N/A),0.0,(N/A),(N/A)
5,Paper Cutters,Epson,(N/A),(N/A),False,(N/A),(N/A),(N/A),False,False,...,0.0,False,0.0,0.0,False,NaN,(N/A),0.0,(N/A),(N/A)
6,Paper Cutters,Epson,(N/A),(N/A),False,(N/A),(N/A),(N/A),False,False,...,0.0,False,0.0,0.0,False,NaN,(N/A),0.0,(N/A),(N/A)

In [6]:
df_column_stats = compute_column_stats(df_data)

In [7]:
df_column_stats.head()

,column,suggested_type,n_unique,len_total,len_min,len_max,len_avg,values,n_filled
0,id,int32,7969,7969,4,8,7.652529,1710 | 1983 | 13397 | 19832 | 20235,7969
1,supplier_id,int32,123,123,1,5,3.739837,1 | 13 | 87 | 189 | 192,7969
2,supplier_name,category,123,122,2,24,7.581967,HP | Epson | Kensington | Brother | Sharp,7961
3,category_id,int32,187,187,3,4,3.673797,718 | 303 | 915 | 495 | 306,7969
4,category_name,category,190,189,5,39,16.100529,Greeting & Sympathy Cards | Fax Machines | Pri...,7961

In [8]:
df_column_stats.to_excel('../data/ice-cat-office-products-column-stats.xlsx')